version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: my_ramen_backend_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/xdebug/log:/tmp
    expose:
      - 9000
    depends_on:
      - db
  web:
    image: nginx:alpine
    container_name: my_ramen_backend_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
      image: mysql:8.0
      container_name: my_ramen_backend_db
      restart: always
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
      volumes:
        - ../mysql_data:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
